### ISSUE TITLE
Is this sdk still maintained

### ISSUE THREAD

**Issue by mpaulon** [scaleway/python-scaleway#43]
I was wondering if this sdk is still maintained by the scaleway team.
It still has support for the non-working `account.scaleway.com` part of the api and doesn't support the new endpoints (like `https://api.scaleway.com/account/v2alpha1/ssh-keys` for managing ssh keys) that are supported in the scaleway go sdk.
Not entirely related to this specific sdk, but this part of the api doesn't seem to be documented anywhere.

**Comment by remyleone** [comment]
We are currently working on a brand new Python SDK with @quantumsheep would you like to be included in a private beta when it will be ready?

**Comment by remyleone** [comment]
I am not. I want to redo those Ansible modules from scratch and generate
them as much as possible. I can't guarantee that the new maintained version
will be compatible with the ones you are developing

**Comment by fmenabe** [comment]
Hi @remyleone 

I've made some Ansible modules for managing DNS and Kubernetes clusters. I was starting to think about making PRs but it felt like a lot of things should not be managed by the modules themselves. So that's why I ended up here!

From what you say, it would be pointless to do too much work on theses modules or try to merge them. They are at a stage where "it works for me" but a lot should be improved before even making the PRs and the review process would probably take a lot of time (for something that will probably change).

Could I also be included in the private beta when ready? And, if it is not too difficult to answer, do you have an idea of when it will be available (not expecting an exact date but is it closer to days, weeks, months)?

PS: I seen an issue about integrating Kops a few weeks ago and its really nice to see there is already a PR for it (from this week apparently :wink:). Really like what you're doing at Scaleway.
